version: "3.8"

services:

    api:
        container_name: api-container
        build: ./flask_api
        restart: always
        
        command: uwsgi --ini app.ini

        volumes: 
            - api_data:/docker_api

    nginx:
        container_name: nginx-container
        build: ./nginx
        restart: always

        ports: 
            - "80:80"
              
        volumes: 
            - api_data:/docker_api
        depends_on: 
            - api

volumes:
    api_data: 